test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run lint

deploy:
  image: ezkrg/buildx
  #image: jdrouet/docker-with-buildx:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  services:
    - name: docker:dind
      alias: docker
  stage: deploy
  script:
    - echo $DOCKER_PW
    - echo $DOCKER_PW | docker login --username supporterino --password-stdin
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --push -t supporterino/wizard:ci . 
  only:
    - tags
