test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run lint

build:
  image: docker:19.03.12
  stage: build
  script:
    - echo $DOCKER_PW | docker login --username supporterino --password-stdin
    - docker build -t supporterino/wizard:ci .
    - docker push supporterino/wizard