test:
  image: node:latest
  stage: test
  script:
    - npm install
    - npm run lint

build:
  image: jdrouet/docker-with-buildx:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  services:
    - name: docker:dind
      alias: docker
  stage: build
  script:
    - echo $DOCKER_PW
    - echo $DOCKER_PW | docker login --username supporterino --password-stdin
    - docker buildx create --use
    - docker buildx build --push --platform linux/arm64/v8,linux/amd64 --push -t supporterino/wizard:ci . 
    #- docker build -t supporterino/wizard:ci .
    #- docker push supporterino/wizard
